name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install mmark
      run: |
        wget https://github.com/mmarkdown/mmark/releases/download/v2.2.4/mmark_2.2.4_linux_amd64.tgz -O/tmp/mmark.tgz && tar xzf /tmp/mmark.tgz       
    - name: Run python script
      run: |
        python3 mkpreview.py
